@startuml
left to right direction

actor Mitarbeiter

rectangle "Verwaltungsfrontend" {
usecase "UC01\nIn System Einloggen" as uc01
usecase "UC02\nPartnerhochschulen Anlegen" as uc02
usecase "UC03\nPartnerhochschulen Editieren" as uc03
usecase "UC04\nDatensätze Löschen" as uc04
usecase "UC05\nMentoren Editieren" as uc05
usecase "UC06\nBerichte Erstellen" as uc06
usecase "UC07\nErstellte Berichte Exportieren" as uc07
}

Mitarbeiter -- uc01
Mitarbeiter -- uc02
Mitarbeiter -- uc03
Mitarbeiter -- uc04
Mitarbeiter -- uc05
Mitarbeiter -- uc06
uc06 <.down. uc07 : extends


actor Nutzer

rectangle "Informationsfrontend" {

usecase "UC08\nBerichte für Externe Anzeigen" as uc08
}
Nutzer -- uc08

@enduml
